endpoints to list sponsors of a group and groups of a user
fedora-infra/fasjson pull request #105
Opened 2020-07-09 12:05 UTC by StephenCoady

The first gives the ability to return a list of sponsors of a group.
The second adds the ability to return the list of groups a user is a member of.

Signed-off-by: Stephen Coady <scoady@redhat.com>

2020-07-10 12:03 UTC, abompard requested changes

2020-07-10 12:03 UTC, abompard commented on fasjson/lib/ldap/client.py
> +            return None
Since we're returning a list, maybe it's better to return an empty list in this case, from an API point of view, no?

2020-07-10 12:03 UTC, abompard commented on fasjson/lib/ldap/client.py
> +            res = self.search(model=UserModel, base_dn=sponsor)
Although there shouldn't be too many sponsors in a group, do you think there would be a way to get them all in one query with the appropriate filter?

2020-07-10 12:03 UTC, abompard commented on fasjson/lib/ldap/client.py
> +            "(&" f"(member={dn},{self.basedn})" f"{GroupModel.filters}" ")"
That's a weird concatenation of strings

2020-07-10 12:03 UTC, abompard commented on fasjson/tests/unit/test_lib_ldap_client.py
> +    ldap = LDAP("https://dummy.com", basedn="dc=example,dc=test")
It's a bit strange to have an "https://" URL for the LDAP client, even if it's just for mocking ;-)

2020-07-10 12:03 UTC, abompard commented on fasjson/web/resources/users.py
> +    @api_v1.doc("list_users_groups")
this should be `_user_`, not `_users_`.

2020-07-10 12:03 UTC, abompard commented on fasjson/web/resources/groups.py
> +    @api_v1.doc("get_group_sponsors")
Hmm this is a bit inconsistent. I'd prefer if methods that return lists are prefixed with `list_`, and methods that return an object are prefixed with `get_`. I know that there's already `get_group_members` that doesn't follow this naming scheme, do you think we could update it and change the apps that we've already made a PR for and that use this endpoint?

2020-07-10 12:03 UTC, abompard commented on fasjson/web/resources/groups.py
> +        """Fetch group members given the group name"""
The docstring need to be updated

2020-07-13 10:58 UTC, StephenCoady commented on fasjson/lib/ldap/client.py
> +            res = self.search(model=UserModel, base_dn=sponsor)
I originally tried to do this but could never quite get it working. Then again my ldap isn't the best. I can take another look though for sure.

2020-07-13 10:59 UTC, StephenCoady commented on fasjson/lib/ldap/client.py
> +            "(&" f"(member={dn},{self.basedn})" f"{GroupModel.filters}" ")"
`black` + me not re-checking what it has done :facepalm:

2020-07-13 11:03 UTC, StephenCoady commented on fasjson/tests/unit/test_lib_ldap_client.py
> +    ldap = LDAP("https://dummy.com", basedn="dc=example,dc=test")
I just used the same line that the other tests use. Should I change them all?

2020-07-13 11:18 UTC, StephenCoady commented on fasjson/web/resources/groups.py
> +    @api_v1.doc("get_group_sponsors")
Sure, I can do that no problem. Just to play devil's advocate - would a better solution be to just make everything `get_`?

2020-07-13 13:10 UTC, abompard commented on fasjson/web/resources/groups.py
> +    @api_v1.doc("get_group_sponsors")
I'm not sure, I think that it's an interesting feature for the user to be able to expect a list when the endpoint starts with `list`, but what's most important to me is that things are consistent.

2020-07-13 13:13 UTC, abompard commented on fasjson/tests/unit/test_lib_ldap_client.py
> +    ldap = LDAP("https://dummy.com", basedn="dc=example,dc=test")
Yeah, if you don't mind

2020-07-14 08:42 UTC, StephenCoady commented on fasjson/web/resources/groups.py
> +    @api_v1.doc("get_group_sponsors")
cool, then I've no problem re-doing the other PRs. I'll push the changes.

2020-07-17 14:47 UTC, abompard requested changes

2020-07-17 14:47 UTC, abompard commented on fasjson/web/resources/groups.py
> +        """Fetch group spoonsors given the group name"""
So I suppose `spoonsors` should help users grow as contributors by spoon-feeding them easyfixes? :-p

2020-07-20 09:28 UTC, StephenCoady commented on fasjson/web/resources/groups.py
> +        """Fetch group spoonsors given the group name"""
Yes, were you not at the meeting where we decided this? :P

2020-07-21 17:17 UTC, abompard approved these changes

2020-07-21 17:28 UTC, merged