return mailing list information about groups
fedora-infra/fasjson pull request #119
Opened 2020-10-27 13:16 UTC by StephenCoady

bugzilla sync toddler uses the email of a group so this change exposes that

Signed-off-by: Stephen Coady <scoady@redhat.com>

2020-10-27 14:50 UTC, abompard commented
This seems fine. Do you want to add the other group attributes (`fasURL` and `fasIRCChannel`) too or do you prefer it being done in a later PR?

2020-10-27 14:57 UTC, StephenCoady commented
I can add them here.

2020-10-28 11:35 UTC, abompard requested changes
Sorry it's a tiny bit more complex than for the mailing-list.

2020-10-28 11:35 UTC, abompard commented on fasjson/lib/ldap/models.py
> +        "irc": Converter("fasircchannel"),
It should be multi-valued, thankfully there's a `multivalued` arg ;-)

2020-10-28 11:35 UTC, abompard commented on fasjson/tests/unit/test_web_resource_v1_groups.py
> +                "irc": f"[#{name}]",
It should be a list, not the string representation of a list.

2020-10-28 11:37 UTC, StephenCoady commented on fasjson/lib/ldap/models.py
> +        "irc": Converter("fasircchannel"),
ah great catch, I forced the tests to pass knowing it should be - but forgot it here.

2020-10-29 08:04 UTC, abompard approved these changes
Thanks!

2020-10-29 08:10 UTC, merged