Add func for case when a group is a sponsor
fedora-infra/fasjson pull request #555
Opened 2023-08-09 14:26 UTC by LenkaSeg

Fixes #444 
Fix by @abompard 

## Proposed Changes
Added missing function for handling a situation when a group sponsor is another group (one or more)

## Verification Steps
- in tiny-stage:
`vagrant up`

user=admin
password=password

Go to https://ipa.tinystage.test/ipa:
- Add a group (for example test-group)
- Add member managers => User Groups => add a group as a sponsor - for example `editors` group

or do the same from command line:
- ssh to auth machine where the fasjson code is
`vagrant ssh auth`
`sudo -i`

- kinit as admin
`kinit admin`
password=password

- add group `editors` as a sponsor of group `test-group`
`ipa group-find-group-add-member --groups editors test-group`

- run the API request to fasjson server
`curl -u : --negotiate https://fasjson.tinystage.test/fasjson/v1/groups/test-group/sponsors/`

Result:
```
{"result": [{"username": "josephthornton", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/josephthornton/"}, {"username": "marthawilson", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/marthawilson/"}, {"username": "ronaldgarcia", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/ronaldgarcia/"}, {"username": "maryking", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/maryking/"}, {"username": "edwardsilva", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/edwardsilva/"}, {"username": "rebeccahayes", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/rebeccahayes/"}, {"username": "brandirobbins", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/brandirobbins/"}, {"username": "chadhoward", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/chadhoward/"}, {"username": "williamyoung", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/williamyoung/"}, {"username": "pamelasmith", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/pamelasmith/"}, {"username": "janetlewis", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/janetlewis/"}, {"username": "andreberry", "uri": "https://fasjson.tinystage.test/fasjson/v1/users/andreberry/"}]}
```

## Additional Notes
 This does not solve the situation with the nested groups.
When the sponsor of a group is another group, we get the users, but not
if there is a nested group.

2023-08-09 14:27 UTC, LenkaSeg commented
Working on fixing the tests.

2023-08-11 12:13 UTC, LenkaSeg commented
Added tests.
For some reason the lines 115-121 in client.py are not seen as tested by coverage, which is weird, because I'm getting prints from there.

2023-08-24 06:26 UTC, abompard requested changes
Thanks! A couple things I noticed:
- I added a commit to change the `re.findall` into an `re.match` call, as the `re.findall` version would find `cn=` strings in the whole of the DN, and therefore would always match. That's what caused the coverage issue.
- please compile the regexps in the module for performance
- please add a news fragment for the changelog
- it would be nice if your commit had a `Fixes: #bugnumber` line to autoclose it.

Feel free to squash my commit into yours, and please rebase on the dev branch while you're at it :-)

2023-08-28 14:06 UTC, LenkaSeg commented
- added `re.compile` of the regex
- added new fragment for the changelog
- added bug number to commit message

2023-08-29 08:36 UTC, abompard requested changes

2023-08-29 08:36 UTC, abompard commented on fasjson/lib/ldap/client.py
> +            group_match = re.match(re.compile("^cn=([^,]+)"), sponsor)
That is not going to bring any speed improvement, because the regex is compiled on every iteration of the loop.
I was suggesting something like:
```python
# top of the file
GROUP_DN_RE = re.compile("^cn=([^,]+)")
USER_DN_RE = re.compile("^uid=([^,]+)")
```
And then in the function:
```python
group_match = GROUP_DN_RE.match(sponsor)
...
user_match = USER_DN_RE.match(sponsor)
```

2023-08-29 08:56 UTC, LenkaSeg commented on fasjson/lib/ldap/client.py
> +            group_match = re.match(re.compile("^cn=([^,]+)"), sponsor)
oops, true, fixing

2023-08-29 09:19 UTC, abompard approved these changes
Nice, thanks for your work on this!

(PS: I find it funny that PR #555 is a fix for issue #444. There, I said it.)

2023-08-31 16:26 UTC, merged