Add rss
fedora-infra/fasjson pull request #558
Opened 2023-08-11 19:16 UTC by phsmoura

Fixes [noggin 1155](https://github.com/fedora-infra/noggin/issues/1155)

## Proposed Changes

* Adding RSS field in fasjson

## Verification Steps

*

## Additional Notes

Adding an RSS field to make it available for the Fedora Planet. The issue related to this pull request was opened in the Noggin repository.

2023-09-01 14:09 UTC, abompard requested changes
Works great!

Please add a news fragment as described [in this doc](https://noggin-aaa.readthedocs.io/en/latest/contributing.html#release-notes).

2023-09-06 16:54 UTC, phsmoura commented
Done! Thanks for reviewing it :)

2023-09-08 07:16 UTC, abompard requested changes
Actually, the news fragment should contain a line that will end up in the changelog. Something like `Add the rssurl field` would work.

2023-09-12 16:52 UTC, abompard approved these changes

2023-09-15 12:27 UTC, merged