Add multivalue to website and rssurl fields
fedora-infra/fasjson pull request #720
Opened 2024-05-28 20:18 UTC by phsmoura

Fixes #719 

## Proposed Changes

* Make `rssurl` and `website` multivalued fields

## Verification Steps

* It needs to pass unit tests at least. List type were added to those fields in `test_lib_ldap_client.py`

2024-05-29 07:38 UTC, abompard commented
Apparently Black wants to reformat a file, please run it (or run `pre-commit install` which will run it on each commit).

2024-05-30 08:30 UTC, abompard approved these changes
Alright, please rebase and it should be good to go.

2024-06-03 08:05 UTC, abompard requested changes
Oh yeah one more thing: please add a changelog entry with towncrier. You can do that with the command:

```
poetry run towncrier create -c 'Make `rssurl` and `website` multivalued fields' 719.feature
```

2024-06-04 07:08 UTC, abompard approved these changes

2024-06-06 08:19 UTC, abompard requested changes
Actually, `fasWebsiteURL` is still set to `SINGLE-VALUE`  in freeipa-fas. This needs to be done first: https://github.com/fedora-infra/freeipa-fas/issues/151

2024-06-18 15:13 UTC, abompard requested changes

2024-06-18 15:13 UTC, abompard commented on fasjson/lib/ldap/models.py
> +        "rssurl": Converter("fasRssURL", multivalued=True),
All the multi-valued attributes end with an "s", so I think we should rename those to `websites` and `rssurls`. However, that would break backwards compatibility, so let's also keep the existing `website` and `rssurl` fields and add the new multi-valued fields.

2024-06-21 10:04 UTC, abompard commented
Quick question: in the planet script, how do you plan to retrieve the list of users that have a RSS feed configured?

2024-06-24 21:52 UTC, phsmoura commented on fasjson/lib/ldap/models.py
> +        "rssurl": Converter("fasRssURL", multivalued=True),
Sorry, I didt know. Just did it, but what about the `Converter`? Do we keep the same name? Please, let me know if it needs more adjustments

2024-06-24 22:17 UTC, phsmoura commented
> Quick question: in the planet script, how do you plan to retrieve the list of users that have a RSS feed configured?

It's using `subprocess` to execute `curl` and retrieve that information. You can find the script line [here](https://github.com/fedora-infra/planet/blob/b86aab3c242c1c455e562c05cb142731ce8efe75/pluto/build_planet.py#L74)
An update is needed to handle the array for the new multi-valued rssurl(s) attribute, but this has already been implemented locally. We just need this PR to be merged to test it.

2024-06-24 22:45 UTC, abompard commented on fasjson/lib/ldap/models.py
> +        "rssurl": Converter("fasRssURL", multivalued=True),
We can keep the same names, but the old ones must stay without `multivalued` for compatibility.

2024-06-26 09:16 UTC, abompard approved these changes
Looks good, thanks!

2024-06-26 09:18 UTC, abompard commented
> It's using `subprocess` to execute `curl` and retrieve that information. You can find the script line [here](https://github.com/fedora-infra/planet/blob/b86aab3c242c1c455e562c05cb142731ce8efe75/pluto/build_planet.py#L74) 

OK, I have a suggestion for this script to make it only return users that have a RSS feed configured, would you be interested? Also, I can propose a way to do it in Python instead of forking a `curl` binary. If you're interested, tell me and I'll send you a PR.

2024-06-26 09:21 UTC, merged