add the ability to search for users
fedora-infra/fasjson pull request #90
Opened 2020-06-09 13:54 UTC by StephenCoady

this commit adds a /users/search/ endpoint to
facilitate the searching of users. currently,
it searches based on username, mail, surname, givenname
and fasIRCNick

Signed-off-by: Stephen Coady <scoady@redhat.com>

2020-06-09 14:57 UTC, abompard requested changes

2020-06-09 14:57 UTC, abompard commented on fasjson/web/resources/users.py
> +@api_v1.route("/search/<search_term>/")
This is going to shadow the URL for a user named `search`. Probably not a big deal but we might as well avoid that. How about `/search/users/<term>`?

2020-06-09 14:57 UTC, abompard commented on fasjson/web/resources/users.py
> +@api_v1.param("search_term", "The term used to find a user or list of users")
Do you think we need to support searching specifically for a search term? Like searching for `uid=foobar`? If we want to achieve that it would be better to switch to query-string-based search terms.

2020-06-09 14:57 UTC, abompard commented on fasjson/web/resources/users.py
> +            f"(&(objectClass=fasUser)(!(nsAccountLock=TRUE))(|(username=*{search_term}*)"
Would `nsAccountLock=FALSE` work instead of `not TRUE`?

2020-06-09 14:57 UTC, abompard commented on fasjson/web/resources/users.py
> +            api_v1.abort(404, "Empty result", search_term=search_term)
I think we should return an empty list if there are no results instead of a 404 error. No? (If yes you must also remove the class decorator for the 404 error)

2020-06-09 14:57 UTC, abompard commented on fasjson/web/resources/users.py
> +    @api_v1.marshal_with(UserModel)
We should use `paged_marshal_with` here to enable pagination.

2020-06-09 14:57 UTC, abompard commented on fasjson/web/resources/users.py
> +        return res.items
When using `paged_marshall_with`,  we should return the whole result object.

2020-06-09 14:57 UTC, abompard commented on fasjson/web/resources/users.py
> +        )
Maybe make a small `search_users` method in the client class, like we do for `get_users`? This would allow the ldap-specific stuff to remain in the ldap module.

2020-06-09 14:57 UTC, abompard commented on docs/usage.rst
> +   {"result": {"username": "admin", "surname": "Administrator", "givenname": "", "emails": ["admin@$(domain)"], "ircnicks": null, "locale": "fr_FR", "timezone": null, "gpgkeyids": null, "creation": "
The search result should be a list.

2020-06-09 15:00 UTC, tiran commented on fasjson/web/resources/users.py
> +            f"(&(objectClass=fasUser)(!(nsAccountLock=TRUE))(|(username=*{search_term}*)"
No, users may not have the attribute. Missing ``nsAccountLock`` is considered equal to FALSE.

2020-06-09 15:06 UTC, tiran requested changes

2020-06-09 15:06 UTC, tiran commented on fasjson/web/resources/users.py
> +            f"(&(objectClass=fasUser)(!(nsAccountLock=TRUE))(|(username=*{search_term}*)"
The LDAP attribute for ``username`` is ``uid``.

```suggestion
            f"(&(objectClass=fasUser)(!(nsAccountLock=TRUE))(|(uid=*{search_term}*)"
```

2020-06-09 15:06 UTC, tiran commented on fasjson/web/resources/users.py
> +            f"(mail=*{search_term}*)(surname=*{search_term}*)(givenname=*{search_term}*)"
It's ``givenName`` and ``sn``.
```suggestion
            f"(mail=*{search_term}*)(sn=*{search_term}*)(givenname=*{search_term}*)"
```

2020-06-09 15:06 UTC, tiran commented on fasjson/web/resources/users.py
> +        filters = (
Very important: you must quote all user strings with ``ldap.filter.escape_filter_chars()``. I don't see an escape call in the code path.

2020-06-09 15:10 UTC, abompard commented on fasjson/web/resources/users.py
> +            f"(&(objectClass=fasUser)(!(nsAccountLock=TRUE))(|(username=*{search_term}*)"
Ah, good to know, thanks.

2020-06-10 09:07 UTC, StephenCoady commented on fasjson/web/resources/users.py
> +            api_v1.abort(404, "Empty result", search_term=search_term)
Yeah I wasn't 100% here as no results still return as an empty list. I had this in as a just in case something goes wrong but your comment made me realise I don't know what that something is. I'll remove it.

2020-06-10 09:10 UTC, tiran commented
I recommend that you require a sensible minimum length for a query (e.g. 3 to 5 chars minimum) and that you limited the result set with a SimplePageResult to maybe 50 or 100 users. Otherwise users can easily overload the system with a query for ``e`` or ``o``.

2020-06-11 09:34 UTC, StephenCoady commented
Thanks for the feedback @tiran and @abompard. I've made the changes you suggested now.

2020-06-11 09:37 UTC, StephenCoady commented on fasjson/web/resources/users.py
> +@api_v1.param("search_term", "The term used to find a user or list of users")
This is the only change I didn't make. At the moment we really only have a few fields that it would be useful to search on (and so far only one app that I've seen use them and it only uses email). I think its actually pretty useful to be able to blanket search based on a single term.

2020-06-11 16:09 UTC, StephenCoady commented
@abompard was this what you had in mind? I tried to make it as neat as possible. its probably not the most "pythonistic" way to do things but maybe you can let me know if not :)

the only thing i wanted to make better was the naming of the arguments. I made them the same as the LDAP attributes so that I could generate the LDAP filter with a lot less code.

2020-06-11 16:55 UTC, abompard requested changes

2020-06-11 16:55 UTC, abompard commented on fasjson/web/resources/search.py
> +    @api_v1.expect(search_request_parser)
Are you sure it works to have multiple parsers stacked like this? According to [the doc](https://flask-restx.readthedocs.io/en/latest/parsing.html#parser-inheritance) inheritance is done by copying and adding.

2020-06-11 16:55 UTC, abompard commented on fasjson/web/resources/search.py
> +        if not args_provided:
Instead of introducing this `args_provided` variable, I would recommend first cleaning up the arguments to remove empty values, and then just testing if the arguments dict is empty (just `if not args` should be enough).

2020-06-11 16:55 UTC, abompard commented on fasjson/lib/ldap/client.py
> +        filter_fields = {
You can actually convert between API names and LDAP names with the models in `fasjson.lib.ldap.models`. If we return "username" as a user's username in the API, it should expect a `username` key for searching, not `uid`. That would be a bit weird.

2020-06-15 15:30 UTC, StephenCoady commented on fasjson/web/resources/search.py
> +    @api_v1.expect(search_request_parser)
it actually did work funnily enough, but I've done it the way the docs recommended now.

2020-06-15 15:31 UTC, StephenCoady commented on fasjson/lib/ldap/client.py
> +        filter_fields = {
realised I didn't need to do this at all stupidly. because we are only searching a few fields I just built that dict and then filtered based on that - the api needn't have changed.

2020-06-15 16:03 UTC, abompard requested changes

2020-06-15 16:03 UTC, abompard commented on fasjson/lib/ldap/client.py
> +        for k, v in escaped.items():
Please avoid variables such as `k`, `v` meaning `key` `value`, the names here are an opportunity to describe what the variables contain. You could use something like `attribute` and `filter` for example.

2020-06-15 16:03 UTC, abompard commented on fasjson/lib/ldap/client.py
> +                filters += f"({k}=*{v}*)"
You could run the `escape_filter_chars()` function here and not have to build the `escaped` dict at all.

2020-06-15 16:03 UTC, abompard commented on fasjson/lib/ldap/client.py
> +            sub_dn=dn,
You don't need to pass that hardcoded value, it will be deduced from the `UserModel` value.

2020-06-15 16:03 UTC, abompard commented on fasjson/lib/ldap/client.py
> +            k: ldap.filter.escape_filter_chars(v, 1) if v is not None else v
You're using the second argument of `escape_filter_chars` to escape all non-ascii chars. Any reason for that? The `surname` and `givenname` values could contain non-ascii chars.

2020-06-15 16:03 UTC, abompard commented on fasjson/web/resources/search.py
> +        page_number = search_args.pop("page", 1)
There's already a default set for that in the parser, you can just use `search_args.page`.

2020-06-15 16:03 UTC, abompard commented on fasjson/web/resources/search.py
> +        args_exist = {k: v for k, v in search_args.items() if v}
You could just do `any(search_args.values())`.

2020-06-15 16:03 UTC, abompard commented on fasjson/web/resources/search.py
> +            api_v1.abort(403, "At least one search term must be provided")
I think another error code would be more appropriate, like 400, since this is unrelated to authentication. (please document it with a decorator too)

2020-06-15 16:03 UTC, abompard commented on fasjson/web/resources/search.py
> +                    403,
Same here.

2020-06-16 08:52 UTC, StephenCoady commented on fasjson/web/resources/search.py
> +        page_number = search_args.pop("page", 1)
Is it OK to still use pop and just not set the default? Because I use `search_args` further down the code to make sure they have provided at least arg - but I can't include `page` or `page_size` in that check.

2020-06-16 08:54 UTC, abompard commented on fasjson/web/resources/search.py
> +        page_number = search_args.pop("page", 1)
Yeah, I'm a bit on the fence about modifying a structure that contains user input, but in this case you can always get that data back by calling `parse_args()` again, so I guess it's OK. In that case, `pop` is fine here too.

2020-06-16 08:55 UTC, StephenCoady commented on fasjson/lib/ldap/client.py
> +            k: ldap.filter.escape_filter_chars(v, 1) if v is not None else v
I hadn't thought of the names. I wasn't sure which of the 3 options to choose really so I settled in the middle. do you think `0` would be better?

2020-06-16 09:16 UTC, StephenCoady commented on fasjson/web/resources/search.py
> +        page_number = search_args.pop("page", 1)
this seems to have broken it now. i'm not sure when the parser adds its default

2020-06-16 09:29 UTC, StephenCoady commented on fasjson/tests/unit/test_web_resource_v1_search.py
> +        search_users=lambda username, email, ircnick, surname, givenname, page_size, page_number: result  # noqa:E501
just in case you are wondering @abompard I think I found a bug in black here. if i shorten this line flake8 is happy but black formatting actually makes it longer again. I am going to file it upstream but for now I thought telling flake8 to ignore a line in a test file was OK.

2020-06-16 12:40 UTC, abompard commented on fasjson/tests/unit/test_web_resource_v1_search.py
> +        search_users=lambda username, email, ircnick, surname, givenname, page_size, page_number: result  # noqa:E501
OK, another solution would be to either declare the function as `lambda *a, **kw: result` or to define a function (inside the test) that takes all those arguments and return result, and just refer to it in the mock.

2020-06-16 13:16 UTC, abompard commented on fasjson/lib/ldap/client.py
> +            k: ldap.filter.escape_filter_chars(v, 1) if v is not None else v
Yeah I think `0` is fine.

2020-06-16 13:18 UTC, abompard commented on fasjson/web/resources/search.py
> +        page_number = search_args.pop("page", 1)
It's in `fasjson.web.utils.pagination`, when the `page` argument is added (btw I should have named it `page_number` and not just `page` but that's another story)

2020-06-19 08:32 UTC, abompard requested changes

2020-06-19 08:32 UTC, abompard commented on fasjson/lib/ldap/client.py
> +        filter_string = "(&(objectClass=fasUser)(!(nsAccountLock=TRUE))(|"
Oh I just realized: we ar OR-ing the search terms here. Is this what we want? Intuitively I'd say we should AND the search terms.

2020-06-19 08:32 UTC, abompard commented on fasjson/lib/ldap/client.py
> +                filter_string += f"({ldap.filter.escape_filter_chars(attribute, 0)}=*{filter}*)"
It's the filter value that should be escaped, since that's the user input. We're pretty safe with the attribute.

2020-06-19 08:32 UTC, abompard commented on fasjson/lib/ldap/client.py
> +        filter_string += "))"
One small detail that is totally not a blocker, more a FYI: in Python it is much faster to create a list of strings and join it than to create a string and append to it multiple times. The reason for that is that strings are immutable objects, so Python has to generate a new one each time it's appended to. So in Python you'll frequently see constructs such as:
```
result = ["beginning"]
for elem in string_list:
    result.append(elem)
result.append("end")
result = "".join(result)
```
rather than appending to the string in the loop.
I don't think it's necessary to change the way you've done it here, it's just so you know.
```

2020-06-19 08:32 UTC, abompard commented on fasjson/tests/unit/test_web_resource_v1_search.py
> +    mock_ldap_client(search_users=lambda *a, **kw: result)
Those 3 lines are almost identical in 3 test functions, maybe it would be better to factor them out in a function.

2020-06-19 08:32 UTC, abompard commented on fasjson/tests/unit/test_web_resource_v1_search.py
> +    expected = [_get_user_api_output(f"dummy-{idx}") for idx in range(1, 2)]
I don't see the difference between this test and the one before.

2020-06-19 08:49 UTC, StephenCoady commented on fasjson/lib/ldap/client.py
> +        filter_string = "(&(objectClass=fasUser)(!(nsAccountLock=TRUE))(|"
yep you're right, i forgot to change this from when it was a blanket search.

2020-06-19 08:51 UTC, StephenCoady commented on fasjson/lib/ldap/client.py
> +                filter_string += f"({ldap.filter.escape_filter_chars(attribute, 0)}=*{filter}*)"
woops

2020-06-19 14:51 UTC, StephenCoady commented on fasjson/lib/ldap/client.py
> +        filter_string += "))"
thats good to know thanks, I'll change it.

2020-06-19 14:51 UTC, StephenCoady commented on fasjson/tests/unit/test_web_resource_v1_search.py
> +    mock_ldap_client(search_users=lambda *a, **kw: result)
reduced to one use now but i'll still factor it out in case we need it in the future

2020-06-19 14:52 UTC, StephenCoady commented on fasjson/tests/unit/test_web_resource_v1_search.py
> +    expected = [_get_user_api_output(f"dummy-{idx}") for idx in range(1, 2)]
again a legacy that makes no sense now, removing

2020-06-20 08:54 UTC, abompard requested changes
Almost there! :-)

2020-06-20 08:54 UTC, abompard commented on fasjson/web/resources/search.py
> +        if page_size and page_size > 40:
If we want to force pagination, we must also check that `page_size > 0`. When set to zero it disables pagination.

2020-06-20 08:54 UTC, abompard commented on fasjson/tests/unit/test_web_resource_v1_search.py
> +    result = LDAPResult(items=[])
You could also factor that if you change your new fixture into a regular function that takes the number of results as a parameter.

2020-06-22 15:40 UTC, abompard commented on fasjson/web/resources/search.py
> +        if isinstance(page_size, int) and (page_size > 40 or page_size < 1):
In which case can we have `page_size` not be an integer? I thought the parser would catch that, did you try?

2020-06-22 15:45 UTC, StephenCoady commented on fasjson/web/resources/search.py
> +        if isinstance(page_size, int) and (page_size > 40 or page_size < 1):
I noticed that when I passed `0` then the if clause here was never triggered unless I told it that `page_size` was an `int`.

2020-06-22 16:28 UTC, abompard commented on fasjson/web/resources/search.py
> +        if isinstance(page_size, int) and (page_size > 40 or page_size < 1):
Sorry but I can't find a way to reproduce that. Could you give me an example? Or even better, write a test that would fail if you don't check for `isinstance`?

2020-06-22 16:39 UTC, StephenCoady commented on fasjson/web/resources/search.py
> +        if isinstance(page_size, int) and (page_size > 40 or page_size < 1):
No worries, there is actually one there already. If you run the tests locally and change line 38 to this:

```
if page_size and (page_size > 40 or page_size < 1):
```

Then the test `test_search_user_page_size_zero` will fail. Or else you can curl with `&page_size=0` and you won't get the "Page size must be between 1 and 40..." error back.

2020-06-22 20:35 UTC, abompard commented on fasjson/web/resources/search.py
> +        if isinstance(page_size, int) and (page_size > 40 or page_size < 1):
Hmm OK but what if you just leave line 38 at `if page_size > 40 or page_size < 1:` ?

2020-06-24 10:23 UTC, tiran commented on fasjson/lib/ldap/client.py
> +                    f"({attribute}=*{ldap.filter.escape_filter_chars(filter, 0)}*)"
It might make sense to not allow wildcard matching for email addresses and require a full match. In the current form ``search_users()`` allows me to get a list of all almost all Red Hat employees with search term ``@redhat.com``.

2020-06-24 11:12 UTC, StephenCoady commented on fasjson/lib/ldap/client.py
> +                    f"({attribute}=*{ldap.filter.escape_filter_chars(filter, 0)}*)"
ah, good point. pushed now.

2020-06-24 12:08 UTC, abompard commented on fasjson/tests/unit/test_lib_ldap_client.py
> +        total=3,
If you don't want a different value of `total`, you can leave it out of the arguments and it will default to the `item`'s length.

2020-06-24 12:08 UTC, abompard commented on fasjson/tests/unit/test_lib_ldap_client.py
> +    expected = LDAPResult(items=[], total=0, page_size=3, page_number=2,)
Same here

2020-06-24 12:08 UTC, abompard commented on fasjson/tests/unit/test_lib_ldap_client.py
> +    expected = LDAPResult(items=[], total=0, page_size=3, page_number=2,)
Same here

2020-06-24 15:40 UTC, abompard approved these changes
LGTM, thanks!

2020-06-24 15:41 UTC, merged